# Generated by Django 4.0.1 on 2022-03-22 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='lobby_code',
        ),
        migrations.AddField(
            model_name='lobby',
            name='lobby_name',
            field=models.CharField(default='Test', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='lobby',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
